<html lang="en">
<? $this->partial('partial/header'); ?>
<style>
    [v-cloak] {
        display : none;
    }
</style>
<v-app id="app">
    <v-main>
        <?=$this->getContent();?>
    </v-main>
    <v-footer app>
        &copy;<?=date('Y')?> Eagle Eye. Written By Tony Mucci for My Company Tools. https://mycotools.com
    </v-footer>
</v-app>
<? $this->assets->outputJs(); ?>
<? $this->partial('partial/footer'); ?>
</body>
</html>

